# Custom parts:

language: R
sudo: false
dist: trusty
cache: packages

warnings_are_errors: true

r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
